# TEAM: frontend_infra
# 
# Override rules in .eslintrc.yaml for CI
# This file will be added to the test run by the
# CI system. These rules will disable rules in
# .eslintrc.yaml to be able to split the test
# runs into two groups (one without import rules
# and one with just import rules)
rules:
  import/no-named-as-default: off
  import/no-extraneous-dependencies: off
  import/no-named-as-default-member: off
  import/no-duplicates: off
  import/default: off
  import/no-unresolved: off
  import/no-self-import: off
  import/extensions: off
