# Tutorials:
# https://www.cloudbees.com/blog/yaml-tutorial-everything-you-need-get-started
# https://www.w3schools.io/file/yaml-arrays/

extends:
  - prettier

plugins:
  - import
  - lodash
  # - jest
  - autofix
  - flowtype

env:
  node: true
  # jest/globals: true
  es2021: true

settings:
  flowtype:
    onlyFilesWithFlowAnnotation: false
  import/ignore:
    - node_modules

parser: "@babel/eslint-parser"

rules:
  camelcase: [error, { properties: always, ignoreDestructuring: false }]
  # Disabled for nodejs. Enable this for front-end.
  no-console: 0
  no-constant-condition: error
  no-redeclare: [error, { builtinGlobals: true }]
  no-restricted-imports:
    [
      error,
      {
        paths:
          [
            {
              name: "lodash",
              importNames:
                [
                  "set",
                  "get",
                  "chain",
                  "bind",
                  "partial",
                  "max",
                  "min",
                  "isFunction",
                  "isBoolean",
                  "isNil",
                  "isUndefined",
                  "isNull",
                  "filter",
                  "reject",
                  "compact",
                  "some",
                  "every",
                  "map",
                  "reduce",
                  "isEmpty",
                  "size",
                  "assign",
                  "merge",
                  "extend",
                ],
              message: "Don't use these lodash methods; any typed.",
            },
          ],
      },
    ]
  # We use leading underscores
  no-underscore-dangle: 0
  no-use-before-define: 0

  # Shadowing isn't a very difficult concept. --dmnd
  no-shadow: 0

  # We want to be able to write named functional components
  prefer-arrow-callback:
    [error, { allowNamedFunctions: true, allowUnboundThis: true }]

  prefer-object-spread: error

  # airbnb uses "allowEmptyReject": true, but unhandled empty promise rejections
  # cause essentially useless sentry errors. It's more valuable to limit promise rejections
  # to error handling specifically.
  prefer-promise-reject-errors: [error, { allowEmptyReject: false }]

  # This isn't very valuable when we have static types, and it gets confused by
  # invariant.
  consistent-return: 0

  #####################
  # IMPORT PLUGIN RULES
  #####################

  import/default: error
  import/extensions: [error, ignorePackages, { js: never, jsx: never }]
  import/first: error
  import/named: error
  import/no-commonjs: error
  import/no-dynamic-require: error
  import/no-extraneous-dependencies: error
  import/no-import-module-exports: error
  import/no-mutable-exports: error
  import/no-relative-packages: error
  import/no-self-import: error
  import/no-unassigned-import: error
  import/no-unresolved: error
  import/no-unused-modules: error
  import/no-useless-path-segments: [error, { noUselessIndex: true }]
  import/no-webpack-loader-syntax: error
  import/order:
    [
      error,
      {
        groups:
          [
            builtin,
            external,
            internal,
            [parent, sibling, index],
            object,
            type,
            unknown,
          ],
        newlines-between: always,
      },
    ]

  #####################
  # LODASH PLUGIN RULES
  #####################

  lodash/callback-binding: error
  lodash/no-extra-args: error
  lodash/unwrap: error
  lodash/collection-return: error
  lodash/no-double-unwrap: error
  lodash/no-unbound-this: error
  lodash/import-scope:
    - error
    - member

  ######################
  # AUTOFIX CUSTOM RULES
  ######################

  autofix/array-bracket-newline:
    - error
    - multiline: true
  autofix/arrow-body-style:
    - error
    - as-needed
  autofix/arrow-parens:
    - error
    - as-needed
  autofix/capitalized-comments:
    - error
    - always
    - ignorePattern: "console"
      ignoreInlineComments: true
      ignoreConsecutiveComments: true
  autofix/dot-notation:
    - error
    - allowKeywords: false
  autofix/eqeqeq:
    - error
    - always
    - null: never
  autofix/implicit-arrow-linebreak: error
  autofix/jsx-quotes:
    - error
    - prefer-double
  autofix/indent:
    - error
    - 2
  autofix/no-unused-vars:
    - error
    - vars: all
      args: all
      argsIgnorePattern: ^_
  autofix/spaced-comment:
    - error
    - always
    - exceptions: ["/", "-+", "*", "-", "="]
      markers:
        - "::"
        - "="
  autofix/no-plusplus: error
  autofix/valid-typeof:
    - error
    - requireStringLiterals: true

  #######################
  # FLOWTYPE PLUGIN RULES
  #######################

  flowtype/boolean-style: [error, boolean]
  flowtype/define-flow-type: error
  flowtype/delimiter-dangle: off
  flowtype/no-dupe-keys: error
  flowtype/no-primitive-constructor-types: error
  flowtype/no-weak-types:
    [error, { "any": false, "Object": true, "Function": true }]
  flowtype/require-parameter-type:
    - error
    - excludeParameterMatch: "^_"
      excludeArrowFunctions: true
  flowtype/require-valid-file-annotation:
    [error, always, { "annotationStyle": block, "strict": true }]
  flowtype/semi: [error, always]
  flowtype/space-before-type-colon: [error, never]
  flowtype/space-before-generic-bracket: [error, never]
  flowtype/type-id-match: [error, "^\\$?([A-Z][a-z0-9]*)+"]
  flowtype/union-intersection-spacing: [error, always]
  flowtype/use-flow-type: [error]
  flowtype/no-types-missing-file-annotation: [error]

  # rules disabled for now due to amount of work needed
  flowtype/require-return-type: off
  flowtype/require-variable-type: off

  # rules disabled because there's no good reason to enable
  flowtype/sort-keys: off

  # Cosmetic rules disabled because we use prettier
  flowtype/generic-spacing: off
  flowtype/space-after-colon: off
  flowtype/object-type-delimiter: off

  ################################
  # TODO: Add custom eslint rules.
  ################################
