// flow-typed signature: 5b958de3ee8b534384e19bfa99530dee
// flow-typed version: <<STUB>>/apollo-server-express_v^3.1.2/flow_v0.158.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-server-express'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-server-express' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-server-express/dist/ApolloServer' {
  declare module.exports: any;
}

declare module 'apollo-server-express/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-server-express/dist/ApolloServer.js' {
  declare module.exports: $Exports<'apollo-server-express/dist/ApolloServer'>;
}
declare module 'apollo-server-express/dist/index' {
  declare module.exports: $Exports<'apollo-server-express/dist'>;
}
declare module 'apollo-server-express/dist/index.js' {
  declare module.exports: $Exports<'apollo-server-express/dist'>;
}
