// flow-typed signature: 01712a877f5c70d3b139dc959ac7a629
// flow-typed version: <<STUB>>/logger_v^0.0.1/flow_v0.158.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'logger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'logger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'logger/logger' {
  declare module.exports: any;
}

// Filename aliases
declare module 'logger/logger.js' {
  declare module.exports: $Exports<'logger/logger'>;
}
