// flow-typed signature: 513904133a71a7a796cc859428788454
// flow-typed version: <<STUB>>/@babel/eslint-parser_v^7.15.0/flow_v0.158.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/eslint-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/eslint-parser' {
  declare module.exports: any;
}
