// flow-typed signature: 7d41ab6f0a9a4b46e714138ebfd2fa0c
// flow-typed version: <<STUB>>/@graphql-tools/schema_v^8.1.2/flow_v0.158.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@graphql-tools/schema'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@graphql-tools/schema' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@graphql-tools/schema/es5' {
  declare module.exports: any;
}

// Filename aliases
declare module '@graphql-tools/schema/es5/index' {
  declare module.exports: $Exports<'@graphql-tools/schema/es5'>;
}
declare module '@graphql-tools/schema/es5/index.js' {
  declare module.exports: $Exports<'@graphql-tools/schema/es5'>;
}
declare module '@graphql-tools/schema/index' {
  declare module.exports: $Exports<'@graphql-tools/schema'>;
}
declare module '@graphql-tools/schema/index.js' {
  declare module.exports: $Exports<'@graphql-tools/schema'>;
}
